name: 'DReAM deploy'
description: 'Deploy an application with DReAM'
inputs:
  workspace: # id of input
    description: 'DReAM workspace to deploy to'
    required: true
  token: # id of input
    description: 'DReAM token'
    required: true
  privateKey: # id of input
    description: 'Workspace private key'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm install -g @novodream/cli-poc
      shell: "bash"

    - run: dream login --token ${{ inputs.token }}
      shell: "bash"

    - env:
        PRIVATE_KEY: ${{ inputs.privateKey }}
        WORKSPACE: ${{ inputs.workspace }}
      run: |
        echo "${PRIVATE_KEY}" > ~/dream-private-${WORKSPACE}.pem
        dream set-private-key -w ${WORKSPACE} ~/dream-private-${WORKSPACE}.pem
      shell: "bash"

    - run: dream init -w ${{ inputs.workspace }}
      shell: "bash"

    - run: dream up
      shell: "bash"
